### ISSUE TITLE
Show end of long path instead of beginning

### ISSUE THREAD

**Issue by afinne** [jit-y/vscode-advanced-open-file#2]
If you have a deep tree structure, the extension only shows the beginning of the path. The more important part is the end of the path, to enable the user to distinguish between different files in the same folder.

**Comment by jit-y** [comment]
Thanks for the issue!

Because in my usage I have not felt so inconvenient that, I have no image to implement it. 
So I don't plan to implement it, but If you do it and open the PR, I'll review it!

**Comment by jit-y** [comment]
I'll close this issue, but if you have any comment, please reopen this!
