### ISSUE TITLE
Support directory opening

### ISSUE THREAD

**Issue by stevenguh** [jit-y/vscode-advanced-open-file#24]
This extension works great for files. I am wondering is there any way we can support directory open only as another command

I am imagining the quick pick will display directories only like
```
.
..
dir1
dir2
```
When click on anything other than `.`, it will navigate to the directory. When the user click on `.`, it will open that folder with the command like the following
```
let uri = Uri.file('/some/path/to/folder');
let success = await commands.executeCommand('vscode.openFolder', uri);
```

**Comment by jit-y** [comment]
Thanks for the issue!

It's probably possible, but I'm not currently planning to add like that feature in this extension.

**Comment by stevenguh** [comment]
Thank you for replying and making this extension. I am wondering would your accept pull request for that feature?

**Comment by jit-y** [comment]
This extension is ported from advanced-open-file in the Atom editor package, so currently I'm not planning on adding any features that are not implemented in advanced-open-file for now.

I think that feature doesn't implement in advanced-open-file, so I'm likely to not accept the PR for it.

**Comment by stevenguh** [comment]
Thank you for letting me know. I will close this issue.
