### ISSUE TITLE
Entire path is selected when popup opens

### ISSUE THREAD

**Issue by Osmose** [jit-y/vscode-advanced-open-file#6]
When the quickpick dialog opens to show the file list, the path in the filter box is selected, meaning that if you immediately start typing, it _replaces_ the existing path instead of appending to it. My muscle memory is refusing to learn anything different, so I'm hitting this almost every time I use the dialog.

I tried looking for a way to change this behavior and couldn't find anything. I asked on StackOverflow and they closed my question for not including an exact code sample of a feature I wasn't sure even existed. Hrmph.

I tried digging in the source code for QuickPick dialogs to see where it focuses the input box and couldn't find the spot to see if it was configurable. This may eventually be a bug to take up with VSCode itself if there's no choice.

**Comment by jit-y** [comment]
Thanks to #12, you can now disable path selection on opening filter box by setting `vscode-advanced-open-file.selectPath` to `false`!

**Comment by jit-y** [comment]
Thanks for the issue!
